language: go

go:
  - "1.13"

before_install:
  - docker swarm init

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted:"; gofmt -d .; exit 1; fi

deploy:
  - provider: script
    script:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push_containers
  on:
    all_branches: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
