language: go

go:
  - "1.13"

sudo: true

script:
  - if [ -n "$(gofmt -l .)" ]; then echo "Go code is not formatted:"; gofmt -d .; exit 1; fi
  - make integration_test

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push
    on:
      all_branches: true

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
